import { motion } from "framer-motion";
import { HiSparkles } from "react-icons/hi";
import { generateAIInsight } from "../../utils/weatherHelpers";
import { useTheme } from "../../context/ThemeContext";

export default function AIInsight({ weather }: { weather: any }) {
  const { theme } = useTheme();
  const isDark = theme === "dark";
  const insight = generateAIInsight(weather);

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.98 }}
      animate={{ opacity: 1, scale: 1 }}
      className="relative overflow-hidden rounded-3xl p-6 md:p-8 bg-gradient-to-br from-fuchsia-600 via-purple-700 to-indigo-700 shadow-2xl"
    >
      <div className="absolute top-0 right-0 w-64 h-64 bg-cyan-400/20 rounded-full blur-3xl" />
      <div className="absolute bottom-0 left-0 w-64 h-64 bg-pink-400/20 rounded-full blur-3xl" />
      <div className="relative">
        <div className="flex items-center gap-2 mb-3">
          <div className="w-10 h-10 rounded-xl bg-white/20 backdrop-blur flex items-center justify-center">
            <HiSparkles className="text-yellow-300 text-xl" />
          </div>
          <div>
            <div className="text-xs uppercase tracking-widest text-white/70">
              AI Weather Insight
            </div>
            <div className="text-white font-display font-semibold">
              Smart Recommendation
            </div>
          </div>
        </div>
        <p
          className={`leading-relaxed ${isDark ? "text-white" : "text-white"}`}
        >
          {insight}
        </p>
        <div className="mt-4 flex items-center gap-2 text-xs text-white/70">
          <span className="w-1.5 h-1.5 rounded-full bg-emerald-300 animate-pulse" />
          Generated by WeatherAI engine
        </div>
      </div>
    </motion.div>
  );
}
